### ISSUE TITLE
Can re-render be made independent, so that multiple hook calls re-render only the affected param?

### ISSUE THREAD

**Issue by asherccohen** [baruchiro/use-route-as-state#122]
**Issue description**
My app has an horizontal split screen, the two areas have different tabs that slide different sections, tabs are independent,

I would like to persist and read params so that a URL can be shared with the correct sections, or to better handle refreshing.
I have noticed that both  useQueryStringKey and useQueryString make the whole page re-render.
Is there a way to avoid that?
Ideally each portion should re-render independently.

To clarify, I've tried co-locating each section into its own component:
- A page component renders <TopSection/> and <BottomSection/>
- Each section has its own useQueryStringKey/useQueryString
 

**What's the expected result?**
Setting top tab (to navigate a different slide on the top part) re-renders only top section..
 

**What's the actual result?**
Setting top tab (to navigate a different slide on the top part) re-renders also bottom section.

**Comment by baruchiro** [comment]
It is a good question. The custom hooks are triggered when the address is changed, and in a simple way, they will re-render the data.

I need to check if we can compare the new data to the previous and maybe avoid re-rendering. Possibly with `useMemo` but I'm not sure.

I'm a little busy, I hope I will be available in this month to take this.

**Comment by asherccohen** [comment]
Ehi!thanks for answering.

There's no rush, I've tried what you suggest myself.

I have wrapped your hook into a custom one and memoize the result, but that didn't work.

Anyway, let me know your findings, it's an interesting library!

**Comment by asherccohen** [comment]
Thanks. I didn't have the time to test again, but I'll double check when I do.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
