### ISSUE TITLE
Setting default values in URL

### ISSUE THREAD

**Issue by louis-sanna-eki** [baruchiro/use-route-as-state#135]
### Use case

I would like to uniquely sync the state with the URL (modulo param permutation). This is not the case when using default, the same state can lead to two distinct url.

### Current behavior
For instance on demo page (https://github.com/baruchiro/use-route-as-state), `const [foo, setFoo] = useQueryStringKey('foo', 'bar')`, the default value of `foo` (`bar`) does not show up in the URL on page load. Then after manual update is does.

**First page load:**
<img width="392" alt="Screenshot 2021-09-26 at 11 56 10" src="https://user-images.githubusercontent.com/85956496/134803025-0de4e4fe-8d17-4bba-88e6-d01fc2b16f97.png">
<img width="514" alt="Screenshot 2021-09-26 at 12 03 15" src="https://user-images.githubusercontent.com/85956496/134803305-8698f1e0-a4fc-47b1-be87-064fbe4d1978.png">

**After changing the `foo` in input and setting it back to `bar`.**
<img width="380" alt="Screenshot 2021-09-26 at 11 56 16" src="https://user-images.githubusercontent.com/85956496/134803024-6ae997a6-a274-400c-a358-bd2198caa42f.png">
<img width="554" alt="Screenshot 2021-09-26 at 11 56 05" src="https://user-images.githubusercontent.com/85956496/134803026-ed8c66de-9c2a-48c8-a395-b66b7ac6db62.png">

Any reco on how to make sure the URL is `https://baruchiro.github.io/use-route-as-state/?foo=bar` on page load?

**Comment by baruchiro** [comment]
Hi, thank you for using the library and sharing with me your concern!

First, you can open the [`Flow.drawio`](https://github.com/baruchiro/use-route-as-state/blob/master/Flow.drawio) file with [diagrams.net - Draw.io](https://app.diagrams.net/), to see when we assigning the default values into the returned object.

I don't remember exactly the decisions I made. Let's think.

1. How do you expect me to support that? By adding an `options` object to enable showing the default values?
2. What about you will not configure a default value, and instead, you will add a `useEffect` to set the value when the component is mounted? (I'm asking to understand the use-case).

**Comment by louis-sanna-eki** [comment]
@baruchiro 

1. I expected it to be the default behaviour.
2. Yes you're right, a simple useEffect is enough for my use-case, I hoped there was a better way to do it.

Thanks for having taken the time to look at this issue.

**Comment by baruchiro** [comment]
OK then, thanks @louis-sanna-eki for your suggestion. I understand it, but I chose to take the another approach, which is also logical, so I will not change it for now.

Thanks again, and feel free to open other issues!
