### ISSUE TITLE
Can't use with npm 8 and react 17

### ISSUE THREAD

**Issue by zwily** [baruchiro/use-route-as-state#155]
When I try to install in a react 17 project and npm 8, I get this:

```
npm ERR! While resolving: 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from use-route-as-state@5.1.1
npm ERR! node_modules/use-route-as-state
npm ERR!   use-route-as-state@"^5.1.1" from the root project
```

I assume this is because `peerDependencies` in `package.json` still lists `^16.0.0` as the react dependency. I have to install with `---legacy-peer-deps` to get it to install. Any chance we can get that fixed?

**Comment by baruchiro** [comment]
Sorry for the late answer, I'm moving my apartment. I guess it can be easy to fix, but I need to understand the change of `peerDependencies` from npm 6 to npm7,8.

If you can take it I will very thank you!

I hope I will get it next week.

**Comment by baruchiro** [comment]
@zwily Sorry my late, I think it's working now, with `v5.2.1`.
