### ISSUE TITLE
'%' in URL leads to exception

### ISSUE THREAD

**Issue by lsund** [baruchiro/use-route-as-state#69]
Reproduce: setQuery({foo: "%bar"}). My expectation would be "...?foo=%25bar", but it leads to an exception.
It seems to be an issue with the encoding/decoding. Please let me know if my expectations are wrong.
Thank you for maintaining this library!

**Comment by baruchiro** [comment]
@lsund Please update me after you trying V2.1.0

**Comment by lsund** [comment]
Updated, works great. Thanks :)
