### ISSUE TITLE
Setting both query string key and route params in one render/effect does not work.  

### ISSUE THREAD

**Issue by alex-kowalczyk** [baruchiro/use-route-as-state#78]
Steps to reproduce
1. Run the following app 
2. Go to `/test/old-slug`
3. Observe the param is added but slug is still old: /test/old-slug?param=new-param  
4. If you reverse the order of setSlugs/setParam, the opposite happens - slug is updated but param not.   

```
import {useEffect} from "react";
import {Route, BrowserRouter, Switch} from "react-router-dom";
import {useQueryStringKey, useRouteParams} from "use-route-as-state";

function TestSlug() {
    const [slugs, setSlugs] = useRouteParams();
    const [param, setParam] = useQueryStringKey('param')

    useEffect(() => {
        setSlugs({slug: 'new-slug'});
        setParam('new-param');
    }, [])

    return <span> Slug: {slugs.slug} Param: {param}</span>
}

function App() {
    return (
            <BrowserRouter>
                <Switch>
                    <Route path="/test/:slug"><TestSlug /></Route>
                </Switch>
            </BrowserRouter>
    )
}
```

They affect the same underlying state (URL string) so this might be actually a result how React works.
A great workaround would be to provide 'useUrlState' allowing to set both route params and query string keys through single setter.

**Comment by baruchiro** [comment]
Thanks for detailed report!
Hope I will take it soon. You are welcome to try to create a PR with your suggestion.

**Comment by baruchiro** [comment]
Hi, just an update. I started to work on this issue, but I take advantage to add and increase the test coverage. So it will take some more time.

**Comment by baruchiro** [comment]
OK, I also think it is a limitation. I asked in SO: https://stackoverflow.com/questions/67726730/react-router-how-to-update-the-route-twice-in-one-render-cycle

Now I will develop your suggestion.

**Comment by itayganor** [comment]
It will be wonderful to have this working. I have just stumbled upon this amazing library. Toda Baruch!

**Comment by baruchiro** [comment]
Working on it right now, I will open it to review if you want. I feel tired so I'm doing it straight-forward and maybe I'm missing something.
